package com.example.utility

object Constants {
    const val TYPE_BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST"
    const val TYPE_UNBLOCK_USER_REQUEST = "TYPE_UNBLOCK_USER_REQUEST"
    const val TYPE_MESSAGE_DELIVERED = "TYPE_MESSAGE_DELIVERED"
    const val TYPE_MESSAGE_SEEN = "TYPE_MESSAGE_SEEN"
    const val TYPE_REGISTER_USER = "TYPE_REGISTER_USER"
    const val TYPE_CHAT_MESSAGE = "TYPE_CHAT_MESSAGE"
    const val TYPE_CONTACT_AVAILABLE = "TYPE_CONTACT_AVAILABLE"
    const val TYPE_USER_LAST_SEEN = "TYPE_USER_LAST_SEEN"
    const val TYPE_USER = "TYPE_USER"
    const val TYPE_CONNECT_TO_SERVER = "TYPE_CONNECT_TO_SERVER"
}